@startuml
class NormalCar {
    + BuildAllWheelDrive() : void
    + BuildBlindSpotMonitor() : void
    + BuildTouchscreen() : void
    + BuildWirelessSmartphoneCharger() : void
    + GetCar() : Car
}
ICarBuilder <|-- NormalCar
NormalCar o-> "car" Car
@enduml
